app:
  host: "0.0.0.0"
  port: 1111
  title: "Inference API"
  description: "API for starting and stopping Detection inference on multiple RTSP streams."
  version: "1.0.0"

mqtt-pub:
  broker: "mqtt.io"
  port: 1234
  topic: "robot/measure/object_detect/{company_name}/{robot_name}"

mqtt-sub:
  broker: "mqtt.io"
  port: 1234
  topic: "robot/measure/object_detect/{company_name}/{robot_name}"

inference:
  model_path: "./pt_files/yolo11n.pt"
  confidence_threshold: 0.3
